#!/data/data/com.termux/files/usr/bin/bash

echo "Updating... (If possible)"
sleep 2
git pull https://github.com/joshilita/newOS
sleep 2
echo "Done!"
sleep 2
echo "Updating toor... (If possible)"
sleep 4
echo "Completed!"
echo "Press CTRL+Z to stop the running OS to complete the update."



echo "This is a test. Please know that there will be errors during your test."
echo ""
echo "There is only one option because this is just a test. 
What do you want to do?
(cd, ls)"
read cd

if (echo "$to" | fgrep -wq -e home);then
echo "You are already home!"
fi

if (echo "$cd" | fgrep -wq -e cd);then
   read -p "what do you want to cd?: " to
else
   echo "unknown, Please try again."
fi
if (echo "$cd" | fgrep -wq -e exit);then
    kill -9 $(pgrep -f toor)
else
    echo "Not a directory! Please try again."
fi
if (echo "$to" | fgrep -wq -e root);then
   echo "Switching to root..." && sleep 2
   echo "You have switched to root! Please wait..."
   sleep 4
   sh ~/newOS/toor
fi

while true; do
echo "There is only one option because this is just a test. 
What do you want to do?
(cd)"
read cd

if (echo "$cd" | fgrep -wq -e cd);then
   read -p "what do you want to cd?: " to
else
   echo "unknown, Please try again."
fi

if (echo "$to" | fgrep -wq -e home);then
    echo "You are already home!"
else
    echo "Not a directory! Please try again."
fi
if (echo "$to" | fgrep -wq -e root);then
   echo "Switching to root..." && sleep 2
   echo "You have switched to root! Please wait..."
   sleep 4
   sh ~/newOS/toor
fi
done
 
