#!/data/data/com.termux/files/usr/bin/bash
echo "You are now in root. Remember this is just a demo or a test. Type ls to find a file you need"

GREENFG="\e[38;5;82m"
REDWEAKFG="\e[38;5;132m"
BBLUEFG="\e[1;38;5;75m"
FOLDERNAMEFG="\e[1;38;5;45m"
ERRORFG="\e[1;38;5;197m"
RESET="\e[0m"
BOLD="\e[1m"

declare -a dirs

function addFile {
  dirs+=( $1 )
}

while true; do
  echo -e -n "(${GREENFG}User${RESET}@${REDWEAKFG}localhost${RESET} ${BBLUEFG}/root${RESET}) ${BOLD}\$${RESET}"
  read input

  if ( echo $input | fgrep -wq -e exit );then
    echo -e "${GREENFG}Exiting...${RESET}"
    exit 0
  fi

  if (echo "$input" | fgrep -wq -e ls);then
    if [[ ${#dirs[@]} == 0 ]]; then
      echo "If no files are found, type mdir to create a directory."
    else
      echo -e "${FOLDERNAMEFG}${dirs[@]}${RESET}"
    fi
  elif (echo "$input" | fgrep -wq -e mdir);then
     read -p "What does your directory name want to be?" dir
     addFile $dir
  else
    echo -e "${ERRORFG}Command not found.${RESET}"
  fi
done
